#!/usr/bin/env bash

set -e

cd sqlite

# https://sqlite.org/compile.html#recommended_compile_time_options
RECOMMENDED="
-DSQLITE_DEFAULT_MEMSTATUS=0
-DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
-DSQLITE_LIKE_DOESNT_MATCH_BLOBS
-DSQLITE_MAX_EXPR_DEPTH=0
-DSQLITE_OMIT_DECLTYPE
-DSQLITE_OMIT_DEPRECATED
-DSQLITE_USE_ALLOCA
-DHAVE_MALLOC_USABLE_SIZE
"

RECOMMENDED_EXTRAS="
-DHAVE_USLEEP
-DHAVE_FDATASYNC
"

EXTENSIONS="
-DSQLITE_USE_URI=1
-DSQLITE_ENABLE_JSON1
-DSQLITE_ENABLE_FTS3
-DSQLITE_ENABLE_FTS3_PARENTHESIS
-DSQLITE_ENABLE_FTS4
-DSQLITE_ENABLE_FTS5
-DSQLITE_ENABLE_RTREE
-DSQLITE_ENABLE_GEOPOLY
"

clang \
  -fPIC \
  -Wall \
  -Wextra \
  -O3 \
  -g \
  -c \
  $RECOMMENDED \
  $RECOMMENDED_EXTRAS \
  $EXTENSIONS \
  -o sqlite3.o \
  sqlite3.c

ar rcs libsqlite3.a sqlite3.o
